allowBuilds:
  '@firebase/util': true
  '@vercel/speed-insights': true
  esbuild: true
  protobufjs: true
  sharp: true
onlyBuiltDependencies:
  - '@firebase/util'
  - '@vercel/speed-insights'
  - esbuild
  - protobufjs
  - sharp
packages:
  - .
